name: Daily Probing

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  probing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run probing
        env:
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        run: python3 scripts/probing.py
